name: Global Scoping Request
description: This issue template is designed to capture the outcomes of a Professional Services Discovery meeting with a customer
title: "Global Scoping Request: [Customer]"
labels: [👥 ps-delivery]
assignees:
  - bdubwalker, bval, nataliebradley, naval-gupta, samuelabdelsayed, umatty
body:
  - type: markdown
    attributes:
      label: Instructions
      description: |
       1. Please enter the outcomes of the Professional Services Discovery meeting with the customer and mark the services requested by placing an "X" between the square braces.
       2. Please also answer the facilitating questions to provide context for the subsequent scoping call.
       3. A detailed entry will trigger a scoping call with a member of the Professional Services team within region.
  - type: dropdown
    attributes:
      label: Regional Director
      description: Name of the Regional Director Responsible
      multiple: false
      options:
        - label: bdubwalker (Default)
        - label: bval
        - label: nataliebradley
        - label: naval-gupta
        - label: samuelabdelsayed
        - label: umatty (Edge)
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
